import {CALIBRATION_FIELD_DEFINITIONS} from "./calibration-field-definitions";
import {CalibrationStudioState, CameraPose, RingPresentationCalibration} from "./calibration-studio.models";

export interface RingconfCalibrationExport {
  schemaVersion: 2;
  projectVersion: string;
  fields: string[];
  compositions: Record<string, {
    rings: Record<string, RingPresentationCalibration>;
    startup: CalibrationStudioState["startup"];
    views: Record<string, unknown>;
  }>;
}

export function createCalibrationExport(state: CalibrationStudioState): RingconfCalibrationExport {
  const rings = [...state.rings].sort((a, b) => a.slot - b.slot);
  const ringRecord: Record<string, RingPresentationCalibration> = {};
  for (const ring of rings) {
    ringRecord[`ring${ring.slot}`] = cloneRing(ring);
  }
  return {
    schemaVersion: 2,
    projectVersion: state.projectVersion,
    fields: CALIBRATION_FIELD_DEFINITIONS
      .filter(field => field.exportable)
      .map(field => field.key)
      .sort(),
    compositions: {
      [state.composition]: {
        rings: ringRecord,
        startup: {
          ...state.startup,
          start: cloneCamera(state.startup.start),
          end: cloneCamera(state.startup.end),
        },
        views: {},
      },
    },
  };
}

export function createCalibrationJson(state: CalibrationStudioState): string {
  return stableStringify(createCalibrationExport(state)) + "\n";
}

export function createCalibrationTypeScript(state: CalibrationStudioState): string {
  return [
    "// Generated by Calibration Studio 2.0. Do not edit manually.",
    "import type {RingconfCalibrationExport} from '../development-admin/calibration-studio/calibration-export';",
    "",
    "export const RINGCONF_CALIBRATION_DEFAULTS: RingconfCalibrationExport = ",
    stableStringify(createCalibrationExport(state), 2),
    " as const;",
    "",
  ].join("\n");
}

export function stableStringify(value: unknown, space = 2): string {
  return JSON.stringify(sortValue(value), null, space);
}

function sortValue(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(sortValue);
  }
  if (value && typeof value === "object") {
    const record = value as Record<string, unknown>;
    const sorted: Record<string, unknown> = {};
    for (const key of Object.keys(record).sort()) {
      sorted[key] = sortValue(record[key]);
    }
    return sorted;
  }
  if (typeof value === "number") {
    if (!Number.isFinite(value)) {
      throw new Error("Calibration export contains a non-finite number.");
    }
    return Number(value.toFixed(8));
  }
  return value;
}

function cloneRing(ring: RingPresentationCalibration): RingPresentationCalibration {
  return {
    slot: ring.slot,
    role: ring.role,
    position: [...ring.position],
    rotationQuaternion: [...ring.rotationQuaternion],
    visible: ring.visible,
  };
}

function cloneCamera(camera: CameraPose): CameraPose {
  return {
    alpha: camera.alpha,
    beta: camera.beta,
    target: [...camera.target],
    projection: {...camera.projection},
  };
}
