import {CalibrationFieldDefinition} from "./calibration-studio.models";

export const CALIBRATION_FIELD_DEFINITIONS: readonly CalibrationFieldDefinition[] = [
  {
    key: "ring.position",
    label: "Position",
    category: "Initiale Ringaufstellung",
    type: "vector3",
    unit: "world",
    help: "Verschiebt nur den Presentation-Root des Rings. RingData, Preis und Geometrie bleiben unveraendert.",
    babylonProperty: "TransformNode.position",
    safeRange: {min: -20, max: 20},
    exportable: true,
  },
  {
    key: "ring.rotationQuaternion",
    label: "Rotation Quaternion",
    category: "Initiale Ringaufstellung",
    type: "quaternion",
    help: "Kanonische sichtbare Ringrotation. Eulerwerte duerfen nur UI-Hilfen sein; exportiert wird Quaternion.",
    babylonProperty: "TransformNode.rotationQuaternion",
    exportable: true,
  },
  {
    key: "ring.visible",
    label: "Sichtbar",
    category: "Initiale Ringaufstellung",
    type: "boolean",
    help: "Schaltet den Presentation-Root ein oder aus. Der Produktzustand wird nicht geloescht.",
    babylonProperty: "TransformNode.setEnabled",
    exportable: true,
  },
  {
    key: "camera.alpha",
    label: "Alpha",
    category: "Startup-Kamera",
    type: "number",
    unit: "rad",
    help: "Horizontaler Winkel der Babylon ArcRotateCamera um das Target.",
    babylonProperty: "ArcRotateCamera.alpha",
    safeRange: {min: -6.28319, max: 6.28319},
    legacyShopwareKey: "webglSettings.camera[0]",
    exportable: true,
  },
  {
    key: "camera.beta",
    label: "Beta",
    category: "Startup-Kamera",
    type: "number",
    unit: "rad",
    help: "Vertikaler Winkel der Babylon ArcRotateCamera. Wird an die Kameralimits geklemmt.",
    babylonProperty: "ArcRotateCamera.beta",
    safeRange: {min: 0.05, max: 3.1},
    legacyShopwareKey: "webglSettings.camera[1]",
    exportable: true,
  },
  {
    key: "camera.target",
    label: "Target",
    category: "Startup-Kamera",
    type: "vector3",
    unit: "world",
    help: "Blickpunkt der Kamera, nicht Kameraposition. Natural Target und kalibrierte Targets bleiben getrennt.",
    babylonProperty: "ArcRotateCamera.target",
    safeRange: {min: -50, max: 50},
    exportable: true,
  },
  {
    key: "camera.orthoHeight",
    label: "Ortho-Hoehe",
    category: "Framing",
    type: "number",
    unit: "world",
    help: "Primaerer Zoomwert bei orthografischer Kamera. Radius ist dann nicht der sichtbare Zoom.",
    babylonProperty: "orthoTop/orthoBottom",
    safeRange: {min: 2, max: 80},
    legacyShopwareKey: "cameraMinOrthoSize",
    exportable: true,
  },
  {
    key: "camera.radius",
    label: "Radius",
    category: "Startup-Kamera",
    type: "number",
    unit: "world",
    help: "Kameraabstand bei Perspektivprojektion; bei Orthographic Camera nicht der sichtbare Zoom.",
    babylonProperty: "ArcRotateCamera.radius",
    safeRange: {min: 1, max: 120},
    legacyShopwareKey: "webglSettings.camera[2]",
    exportable: true,
  },
  {
    key: "camera.screenOffsetX",
    label: "Screen Offset X",
    category: "Framing",
    type: "number",
    unit: "ratio",
    help: "Seitliche Frustum-Verschiebung relativ zur Ortho-Hoehe.",
    babylonProperty: "orthoLeft/orthoRight",
    safeRange: {min: -1, max: 1},
    exportable: true,
  },
  {
    key: "camera.screenOffsetY",
    label: "Screen Offset Y",
    category: "Framing",
    type: "number",
    unit: "ratio",
    help: "Vertikale Frustum-Verschiebung relativ zur Ortho-Hoehe.",
    babylonProperty: "orthoTop/orthoBottom",
    safeRange: {min: -1, max: 1},
    exportable: true,
  },
  {
    key: "startup.delayMs",
    label: "Verzoegerung",
    category: "Kamerafahrt",
    type: "number",
    unit: "ms",
    help: "Wartezeit nach stabilem Startbild, bevor die Startup-Fahrt beginnt.",
    safeRange: {min: 0, max: 10000},
    exportable: true,
  },
  {
    key: "startup.durationMs",
    label: "Dauer",
    category: "Kamerafahrt",
    type: "number",
    unit: "ms",
    help: "Explizite, FPS-unabhaengige Dauer der Kamerafahrt.",
    safeRange: {min: 0, max: 20000},
    exportable: true,
  },
  {
    key: "startup.easing",
    label: "Easing",
    category: "Kamerafahrt",
    type: "enum",
    help: "Interpolationskurve. Legacy exponential bildet die alte Shopware-Annäherung als Kompatibilitaetsmodus ab.",
    legacyShopwareKey: "factor 0.05 / epsilon 0.001",
    exportable: true,
  },
] as const;

export function getCalibrationFieldDefinition(key: string): CalibrationFieldDefinition {
  const definition = CALIBRATION_FIELD_DEFINITIONS.find(field => field.key === key);
  if (!definition) {
    throw new Error(`Missing calibration field definition for ${key}`);
  }
  return definition;
}
