import {RingPresetSlot} from "../../preset-slots";
import {createCalibrationJson, createCalibrationTypeScript} from "./calibration-export";
import {CalibrationStudioState} from "./calibration-studio.models";

describe("calibration export", () => {
  it("creates deterministic JSON", () => {
    const first = createCalibrationJson(state());
    const second = createCalibrationJson(state());
    expect(first).toBe(second);
    expect(JSON.parse(first).schemaVersion).toBe(2);
    expect(first).toContain('"wedding-pair"');
  });

  it("creates deterministic TypeScript without customer data", () => {
    const output = createCalibrationTypeScript(state());
    expect(output).toContain("RINGCONF_CALIBRATION_DEFAULTS");
    expect(output).toContain("Generated by Calibration Studio 2.0");
    expect(output).not.toContain("preset_");
  });
});

function state(): CalibrationStudioState {
  return {
    schemaVersion: 2,
    projectVersion: "2.7.10",
    composition: "wedding-pair",
    dirty: false,
    rings: [
      {
        slot: RingPresetSlot.WeddingMale,
        role: "wedding-male",
        position: [1, 0, 0],
        rotationQuaternion: [0, 0, 0, 1],
        visible: true,
      },
      {
        slot: RingPresetSlot.WeddingFemale,
        role: "wedding-female",
        position: [0, 0, 0],
        rotationQuaternion: [0, 0, 0, 1],
        visible: true,
      },
    ],
    startup: {
      enabled: true,
      delayMs: 0,
      durationMs: 1200,
      easing: "ease-in-out",
      interruptOnUserInput: true,
      start: {
        alpha: -3,
        beta: 1.2,
        target: [0, 10, 0],
        projection: {mode: "orthographic", orthoHeight: 20, radius: 30, screenOffsetX: 0, screenOffsetY: 0},
      },
      end: {
        alpha: -1.5,
        beta: 1.2,
        target: [0, 10, 0],
        projection: {mode: "orthographic", orthoHeight: 20, radius: 30, screenOffsetX: 0, screenOffsetY: 0},
      },
    },
  };
}
